language: python
sudo: false
branches:
    only:
        - master
        - /^\d\.\d+$/

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=py27-parsel
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=py36-parsel
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true


install:
    - pip install -U pip tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip

deploy:
    provider: pypi
    user: "…"
    password:
        secure: "…"
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
        tags: true
